### ISSUE TITLE
Error al instalar l10n_ec_invoice_sequence

### ISSUE THREAD

**Issue by andesti** [odoo-ecuador/odoo-ecuador#109]
Tengo el siguiente error al instalar l10n_ec_invoice_sequence:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Odoo 8\server.\openerp\http.py", line 543, in _handle_exception
  File "C:\Program Files (x86)\Odoo 8\server.\openerp\http.py", line 580, in dispatch
  File "C:\Program Files (x86)\Odoo 8\server.\openerp\http.py", line 316, in _call_function
  File "C:\Program Files (x86)\Odoo 8\server.\openerp\service\model.py", line 118, in wrapper
  File "C:\Program Files (x86)\Odoo 8\server.\openerp\http.py", line 313, in checked_call
  File "C:\Program Files (x86)\Odoo 8\server.\openerp\http.py", line 809, in __call__
  File "C:\Program Files (x86)\Odoo 8\server.\openerp\http.py", line 409, in response_wrap
  File "C:\Program Files (x86)\Odoo 8\server\openerp\addons\web\controllers\main.py", line 948, in call_button
  File "C:\Program Files (x86)\Odoo 8\server\openerp\addons\web\controllers\main.py", line 936, in _call_kw
  File "C:\Program Files (x86)\Odoo 8\server.\openerp\api.py", line 268, in wrapper
  File "C:\Program Files (x86)\Odoo 8\server\openerp\addons\base\module\module.py", line 447, in button_immediate_install
  File "C:\Program Files (x86)\Odoo 8\server.\openerp\api.py", line 268, in wrapper
  File "C:\Program Files (x86)\Odoo 8\server\openerp\addons\base\module\module.py", line 495, in _button_immediate_function
  File "C:\Program Files (x86)\Odoo 8\server.\openerp\modules\registry.py", line 370, in new
  File "C:\Program Files (x86)\Odoo 8\server.\openerp\modules\loading.py", line 355, in load_modules
  File "C:\Program Files (x86)\Odoo 8\server.\openerp\modules\loading.py", line 255, in load_marked_modules
  File "C:\Program Files (x86)\Odoo 8\server.\openerp\modules\loading.py", line 143, in load_module_graph
  File "C:\Program Files (x86)\Odoo 8\server.\openerp\modules\module.py", line 315, in load_openerp_module
  File "C:\Program Files (x86)\Odoo 8\server.\openerp\modules\module.py", line 80, in load_module
  File "C:\Program Files (x86)\Odoo 8\server\openerp\addons\l10n_ec_invoice_sequence__init__.py", line 24, in <module>
  File "C:\Program Files (x86)\Odoo 8\server\openerp\addons\l10n_ec_invoice_sequence\invoice.py", line 25, in <module>
ImportError: No module named tools.translate

**Comment by ovnicraft** [comment]
@andesti que version de la localizacion estas usando ? asegurate que sea la 8.0

**Comment by andesti** [comment]
Gracias @ovnicraft estoy usando Versión 8.0-20160719

**Comment by ovnicraft** [comment]
Puedes bajar el ZIP 8.0 o en los releases, esta actualizado.

**Comment by andesti** [comment]
perfecto, voy a bajarlo, estaba usando el de la página de Odoo 8.0 latest

**Comment by andesti** [comment]
@ovnicraft  en que directorio esta el zip? dentro de Odoo - Ecuador?

**Comment by andesti** [comment]
Bajé la versión 8.0 de este enlace https://nightly.odoo.com/8.0/nightly/exe/odoo_8.0.latest.exe pero me da el mismo error, hay algún orden de instalación especial? así es como lo hice:
1. Crear BD en Inglés
2. Editar Usuario Administrator - Técnico
3. Update Module List
4. Accounting and Finance
5. Sales Management
6. Point of Sale
7. Warehouse Management
8. Purchase Management
9. Address book
10. Employee Directory
11. Notes
12. Calendar
13. Point of Sale Discounts
14. Descargar Lenguaje Español (Ecuador)
15. Open ERP Partner for Ecuador
16. OpenERP OTE for Ecuador
17. SRI Authorization Documents
18. Accounting for Ecuador - Withdrawing
19. Accounting for Ecuador - Invoice Sequence y da el error comentado en el primer mensaje: No module named tools.translate

Estoy usando el plan de cuentas de Cubik para Ecuador

**Comment by ovnicraft** [comment]
Voy a revisar, el store de odoo no esta actualizando los módulos para este proyecto.

**Comment by andesti** [comment]
Gracias, también me baje los paquetes desde GitHub y tengo el mismo problema

**Comment by andesti** [comment]
Voy a probar con una version de 8.0 del año pasado, cuando termine les paso los datos

**Comment by andesti** [comment]
@ovnicraft Hice pruebas con 3 versiones diferentes y todas me dan el mismo error, será que el orden de instalación está mal?

**Comment by ovnicraft** [comment]
El problema no es la version de odoo, es los modulos de localizacion que estas usando, es necesario que descargues que este proyecto la ultima version de estos módulos o actualizarlos si los bajaste desde el app store.

**Comment by andesti** [comment]
@ovnicraft Estoy usando los descargados del proyecto, me los bajé el lunes en ZIP

**Comment by andesti** [comment]
@ovnicraft Listo! me descargue el código con GitHub Desktop, el zip descarga archivos del 2014, tuve que instalar el modulo STDNUM que no está disponible en Odoo 8, ahora todo está funcionando, voy a revisar la localización y si tengo mejoras o sugerencias las hago.

Gracias por la guia.

**Comment by ovnicraft** [comment]
@andesti excelente ! toda recomendación es bienvenida.

**Comment by jcsuscriptor** [comment]
Tenia el mismo error, lo solucione cambiando la linea del import en el archivo "invoice.py"

Esta de esta forma:
from tools.translate import _

Lo cambia a:
from openerp.tools.translate import _

No conozco mucho de python, odoo, me base en este link:

https://bugs.launchpad.net/openerp-swiss-localization/+bug/1329683

**Comment by ovnicraft** [comment]
@jcsuscriptor gracias por el reporte, voy a actualizar el codigo.

**Comment by steven19734** [comment]
saludos, quiero instalar el modulo de facturación electrónica, tengo un problema "hay una dependencia externa no resuelta: No module named stdnum". Odoo lo tengo Windows 10, Instalé python y apliqué "pip install python-stdnum" en CMD pero no funciona. Pienso que la ruta de instalación no es la correcta para que funcione con odoo. Saben como debo instalar "studnum" para odoo en Windows 10??. Muchas gracias...¡¡

**Comment by ovnicraft** [comment]
@steven19734 Puedes referirte aca https://pypi.python.org/pypi/python-stdnum
