### ISSUE TITLE
Error al escoger Cliente en Pedido de Venta

### ISSUE THREAD

**Issue by andesti** [odoo-ecuador/odoo-ecuador#113]
Hola, me sale este error al ingresar un pedido de venta, cuando escojo el cliente:
Traceback (most recent call last):
  File "C:\Program Files (x86)\Odoo 8.0\server.\openerp\http.py", line 543, in _handle_exception
  File "C:\Program Files (x86)\Odoo 8.0\server.\openerp\http.py", line 580, in dispatch
  File "C:\Program Files (x86)\Odoo 8.0\server.\openerp\http.py", line 316, in _call_function
  File "C:\Program Files (x86)\Odoo 8.0\server.\openerp\service\model.py", line 118, in wrapper
  File "C:\Program Files (x86)\Odoo 8.0\server.\openerp\http.py", line 313, in checked_call
  File "C:\Program Files (x86)\Odoo 8.0\server.\openerp\http.py", line 809, in __call__
  File "C:\Program Files (x86)\Odoo 8.0\server.\openerp\http.py", line 409, in response_wrap
  File "C:\Program Files (x86)\Odoo 8.0\server\openerp\addons\web\controllers\main.py", line 944, in call_kw
  File "C:\Program Files (x86)\Odoo 8.0\server\openerp\addons\web\controllers\main.py", line 936, in _call_kw
  File "C:\Program Files (x86)\Odoo 8.0\server.\openerp\api.py", line 268, in wrapper
  File "C:\Program Files (x86)\Odoo 8.0\server\openerp\addons\l10n_ec_partner\partner.py", line 24, in name_search
  File "C:\Program Files (x86)\Odoo 8.0\server.\openerp\api.py", line 268, in wrapper
  File "C:\Program Files (x86)\Odoo 8.0\server\openerp\addons\base\res\res_partner.py", line 615, in name_get
  File "C:\Program Files (x86)\Odoo 8.0\server.\openerp\api.py", line 268, in wrapper
  File "C:\Program Files (x86)\Odoo 8.0\server\openerp\addons\base\res\res_partner.py", line 821, in _display_address
KeyError: u'city_name'

Alguna idea?

**Comment by ovnicraft** [comment]
No es un cambio que hemos implementado, el metodo _display_address esta usando el campo city_name, no lo encuentra y por eso se cae.
Habra que revisar a fondo esto.

**Comment by andesti** [comment]
Para solucionar el tema lo que hice fue editar el FormVista y cambiar el código así:

Original:
context="{'search_default_customer':1, 'show_address': 1}" options='{"always_reload": True}'

Cambio para solucionar el problema (eliminar el show_address):
context="{'search_default_customer':1}" options='{"always_reload": True}'

Me sirve como está.
