### ISSUE TITLE
Error al buscar cliente en la ventana factura de cliente

### ISSUE THREAD

**Issue by CarlosJVizcaya** [odoo-ecuador/odoo-ecuador#120]
Traceback (most recent call last):
  File "/home/cjva/desarrollo/sources/odoo/openerp/http.py", line 543, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/cjva/desarrollo/sources/odoo/openerp/http.py", line 580, in dispatch
    result = self._call_function(*_self.params)
  File "/home/cjva/desarrollo/sources/odoo/openerp/http.py", line 316, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/home/cjva/desarrollo/sources/odoo/openerp/service/model.py", line 118, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/home/cjva/desarrollo/sources/odoo/openerp/http.py", line 313, in checked_call
    return self.endpoint(_a, *_kw)
  File "/home/cjva/desarrollo/sources/odoo/openerp/http.py", line 809, in __call__
    return self.method(_args, *_kw)
  File "/home/cjva/desarrollo/sources/odoo/openerp/http.py", line 409, in response_wrap
    response = f(_args, *_kw)
  File "/home/cjva/desarrollo/sources/odoo/addons/web/controllers/main.py", line 944, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/cjva/desarrollo/sources/odoo/addons/web/controllers/main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, _args, *_kwargs)
  File "/home/cjva/desarrollo/sources/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/cjva/desarrollo/sources/odoo/addons/odoo-ecuador/l10n_ec_partner/partner.py", line 28, in name_search
    return self.name_get(cr, uid, ids, context)
  File "/home/cjva/desarrollo/sources/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/cjva/desarrollo/sources/odoo/openerp/addons/base/res/res_partner.py", line 615, in name_get
    name = name + "\n" + self._display_address(cr, uid, record, without_company=True, context=context)
  File "/home/cjva/desarrollo/sources/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/cjva/desarrollo/sources/odoo/openerp/addons/base/res/res_partner.py", line 821, in _display_address
    return address_format % args
KeyError: u'city_name'

**Comment by CarlosJVizcaya** [comment]
Me di cuenta que faltaba instalar un modulo, se deberian resolver las dependencias para que no ocurran estos errores.

Saludos

**Comment by ovnicraft** [comment]
@CarlosJVizcaya tuvimos un reporte de este tipo antes. No implementamos una solucion de ese nivel. El error puede estar en odoo, como lo resolviste y que modulo instalaste despues ?
