### ISSUE TITLE
error instalando el modulo Basic Account Reportes

### ISSUE THREAD

**Issue by CarlosJVizcaya** [odoo-ecuador/odoo-ecuador#121]
Traceback (most recent call last):
  File "/home/cjva/desarrollo/sources/odoo/openerp/http.py", line 543, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/cjva/desarrollo/sources/odoo/openerp/http.py", line 580, in dispatch
    result = self._call_function(*_self.params)
  File "/home/cjva/desarrollo/sources/odoo/openerp/http.py", line 316, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/home/cjva/desarrollo/sources/odoo/openerp/service/model.py", line 118, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/home/cjva/desarrollo/sources/odoo/openerp/http.py", line 313, in checked_call
    return self.endpoint(_a, *_kw)
  File "/home/cjva/desarrollo/sources/odoo/openerp/http.py", line 809, in __call__
    return self.method(_args, *_kw)
  File "/home/cjva/desarrollo/sources/odoo/openerp/http.py", line 409, in response_wrap
    response = f(_args, *_kw)
  File "/home/cjva/desarrollo/sources/odoo/addons/web/controllers/main.py", line 948, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/cjva/desarrollo/sources/odoo/addons/web/controllers/main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, _args, *_kwargs)
  File "/home/cjva/desarrollo/sources/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/cjva/desarrollo/sources/odoo/openerp/addons/base/module/module.py", line 447, in button_immediate_install
    return self._button_immediate_function(cr, uid, ids, self.button_install, context=context)
  File "/home/cjva/desarrollo/sources/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/cjva/desarrollo/sources/odoo/openerp/addons/base/module/module.py", line 495, in _button_immediate_function
    registry = openerp.modules.registry.RegistryManager.new(cr.dbname, update_module=True)
  File "/home/cjva/desarrollo/sources/odoo/openerp/modules/registry.py", line 370, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/cjva/desarrollo/sources/odoo/openerp/modules/loading.py", line 355, in load_modules
    loaded_modules, update_module)
  File "/home/cjva/desarrollo/sources/odoo/openerp/modules/loading.py", line 255, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/home/cjva/desarrollo/sources/odoo/openerp/modules/loading.py", line 176, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/home/cjva/desarrollo/sources/odoo/openerp/modules/loading.py", line 118, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/home/cjva/desarrollo/sources/odoo/openerp/tools/convert.py", line 900, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/home/cjva/desarrollo/sources/odoo/openerp/tools/convert.py", line 973, in convert_xml_import
    doc = etree.parse(xmlfile)
  File "lxml.etree.pyx", line 3239, in lxml.etree.parse (src/lxml/lxml.etree.c:69970)
  File "parser.pxi", line 1770, in lxml.etree._parseDocument (src/lxml/lxml.etree.c:102272)
  File "parser.pxi", line 1790, in lxml.etree._parseFilelikeDocument (src/lxml/lxml.etree.c:102531)
  File "parser.pxi", line 1685, in lxml.etree._parseDocFromFilelike (src/lxml/lxml.etree.c:101457)
  File "parser.pxi", line 1134, in lxml.etree._BaseParser._parseDocFromFilelike (src/lxml/lxml.etree.c:97084)
  File "parser.pxi", line 582, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/lxml.etree.c:91290)
  File "parser.pxi", line 683, in lxml.etree._handleParseResult (src/lxml/lxml.etree.c:92476)
  File "parser.pxi", line 622, in lxml.etree._raiseParseError (src/lxml/lxml.etree.c:91772)
XMLSyntaxError: Document is empty, line 1, column 1

**Comment by ovnicraft** [comment]
@CarlosJVizcaya es un modulo obsoleto que no lo usamos ya, el motor de reportes de odoo resuelve todas las necesidades basicas de una empresa.

Dejo este issue para remover el modulo del repo.

**Comment by ovnicraft** [comment]
Es modulo fue removido.
