### ISSUE TITLE
Error al tratar de Validar una factura

### ISSUE THREAD

**Issue by CarlosJVizcaya** [odoo-ecuador/odoo-ecuador#122]
Buenos dias, al tratar de validar una factura recibo el siguiente error:

Traceback (most recent call last):
  File "/home/cjva/desarrollo/sources/odoo/openerp/http.py", line 543, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/cjva/desarrollo/sources/odoo/openerp/http.py", line 580, in dispatch
    result = self._call_function(*_self.params)
  File "/home/cjva/desarrollo/sources/odoo/openerp/http.py", line 316, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/home/cjva/desarrollo/sources/odoo/openerp/service/model.py", line 118, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/home/cjva/desarrollo/sources/odoo/openerp/http.py", line 313, in checked_call
    return self.endpoint(_a, *_kw)
  File "/home/cjva/desarrollo/sources/odoo/openerp/http.py", line 809, in __call__
    return self.method(_args, *_kw)
  File "/home/cjva/desarrollo/sources/odoo/openerp/http.py", line 409, in response_wrap
    response = f(_args, *_kw)
  File "/home/cjva/desarrollo/sources/odoo/addons/web/controllers/main.py", line 955, in exec_workflow
    return request.session.exec_workflow(model, id, signal)
  File "/home/cjva/desarrollo/sources/odoo/openerp/http.py", line 1117, in exec_workflow
    r = self.proxy('object').exec_workflow(self.db, self.uid, self.password, model, signal, id)
  File "/home/cjva/desarrollo/sources/odoo/openerp/http.py", line 885, in proxy_method
    result = dispatch_rpc(self.service_name, method, args)
  File "/home/cjva/desarrollo/sources/odoo/openerp/http.py", line 115, in dispatch_rpc
    result = dispatch(method, params)
  File "/home/cjva/desarrollo/sources/odoo/openerp/service/model.py", line 37, in dispatch
    res = fn(db, uid, _params)
  File "/home/cjva/desarrollo/sources/odoo/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, *_kwargs)
  File "/home/cjva/desarrollo/sources/odoo/openerp/service/model.py", line 188, in exec_workflow
    return exec_workflow_cr(cr, uid, obj, signal, _args)
  File "/home/cjva/desarrollo/sources/odoo/openerp/service/model.py", line 182, in exec_workflow_cr
    return execute_cr(cr, uid, obj, 'signal_workflow', [res_id], signal)[res_id]
  File "/home/cjva/desarrollo/sources/odoo/openerp/service/model.py", line 164, in execute_cr
    return getattr(object, method)(cr, uid, *args, *_kw)
  File "/home/cjva/desarrollo/sources/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/cjva/desarrollo/sources/odoo/openerp/models.py", line 3571, in signal_workflow
    result[res_id] = workflow.trg_validate(uid, self._name, res_id, signal, cr)
  File "/home/cjva/desarrollo/sources/odoo/openerp/workflow/__init__.py", line 85, in trg_validate
    return WorkflowService.new(cr, uid, res_type, res_id).validate(signal)
  File "/home/cjva/desarrollo/sources/odoo/openerp/workflow/service.py", line 91, in validate
    res2 = wi.validate(signal)
  File "/home/cjva/desarrollo/sources/odoo/openerp/workflow/instance.py", line 80, in validate
    wi.process(signal=signal, force_running=force_running, stack=stack)
  File "/home/cjva/desarrollo/sources/odoo/openerp/workflow/workitem.py", line 120, in process
    ok = self._split_test(activity['split_mode'], signal, stack)
  File "/home/cjva/desarrollo/sources/odoo/openerp/workflow/workitem.py", line 248, in _split_test
    self._join_test(t[0], t[1], stack)
  File "/home/cjva/desarrollo/sources/odoo/openerp/workflow/workitem.py", line 257, in _join_test
    WorkflowItem.create(self.session, self.record, activity, inst_id, stack=stack)
  File "/home/cjva/desarrollo/sources/odoo/openerp/workflow/workitem.py", line 95, in create
    workflow_item.process(stack=stack)
  File "/home/cjva/desarrollo/sources/odoo/openerp/workflow/workitem.py", line 116, in process
    if not self._execute(activity, stack):
  File "/home/cjva/desarrollo/sources/odoo/openerp/workflow/workitem.py", line 162, in _execute
    returned_action = self.wkf_expr_execute(activity)
  File "/home/cjva/desarrollo/sources/odoo/openerp/workflow/workitem.py", line 313, in wkf_expr_execute
    return self.wkf_expr_eval_expr(activity['action'])
  File "/home/cjva/desarrollo/sources/odoo/openerp/workflow/workitem.py", line 291, in wkf_expr_eval_expr
    result = eval(line, env, nocopy=True)
  File "/home/cjva/desarrollo/sources/odoo/openerp/tools/safe_eval.py", line 314, in safe_eval
    return eval(c, globals_dict, locals_dict)
  File "", line 1, in <module>
  File "/home/cjva/desarrollo/sources/odoo/openerp/api.py", line 266, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/home/cjva/desarrollo/sources/odoo/openerp/api.py", line 592, in new_api
    result = method(self._model, cr, uid, self.ids, _args, *_old_kwargs)
  File "/home/cjva/desarrollo/sources/odoo/addons/odoo-ecuador/l10n_ec_invoice_sequence/invoice.py", line 66, in action_number
    ref = self._convert_ref(cr, uid, number)
ValueError: "'account.invoice' object has no attribute '_convert_ref'" while evaluating
u'action_number()'

**Comment by ovnicraft** [comment]
@CarlosJVizcaya factura de cliente o proveedor ?

**Comment by CarlosJVizcaya** [comment]
Factura de cliente!

**Comment by ovnicraft** [comment]
Fue corregido este issue.
