### ISSUE TITLE
Campos en V9

### ISSUE THREAD

**Issue by ocurieles** [odoo-ecuador/odoo-ecuador#139]
Hola Señores, buenas noches, he visto que han comenzado la migración a la versión 9, felicitaciones, queria preguntarles que finalidad tiene el tener en la factura de venta el fiscal position ? si se supone que  en el cliente ya le seteas ese valor, para que tener que hacer que el usuario lo coloque de nuevo ? 

Saludos

**Comment by ovnicraft** [comment]
@ocurieles Si se configura en el cliente ya el sistema lo configura automaticamente en la factura.

**Comment by ocurieles** [comment]
Gracias por la respuesta Cristian, pero que finalidad tiene ? no son datos duplicados ?  de todos modos en la V9 lo probe y no lo esta colocando automaticamente.

Saludos

**Comment by ovnicraft** [comment]
No, ya que el documento recibido, por ejemplo una factura en un caso el proveedor es un tipo de contribuyente y puede suceder en el tiempo que el proveedor cambia el tipo de contribuyente y eso se cambia en el partner, sin embargo se requiere que en cada documento se registre el tipo de contribuyente de ese momento.

Cierro el issues, cualquier comentario lo podemos seguir.

**Comment by ocurieles** [comment]
Creeria que la información se puede buscar en el partner.. pero es decision de ustedes.

 Saludos

**Comment by mhernandezve** [comment]
Hola amigos: 
@ocurieles estuve pensando en éste asunto y obviamente se puede buscar en el proveedor pero creo que es buena idea guardarlo en cada documento ya que se tiene la historia del tipo de contribuyente que era el proveedor en ese momento.

**Comment by ocurieles** [comment]
De acuerdo @mhernandezve solo que esta pidiendole al usuario colocar esa info, por eso se nota la redundancia, creo que se debe corregir es que lo autoasigne.

Saludos.

**Comment by mhernandezve** [comment]
Creo que lo importante allí es que el usuario no tenga que ingresarlo en la factura si no que se coloque por defecto el que tiene el proveedor en el momento.

**Comment by ovnicraft** [comment]
El funcionamiento actual es ese, el que tiene el proveedor lo asigna en ese momento.

**Comment by ocurieles** [comment]
Pero en cliente no lo hace.... es lo que te digo, tuve que ir a la otra pestaña en la factura a colocarlo.

Saludos

**Comment by ovnicraft** [comment]
Habra que revisar, segun esto https://github.com/odoo/odoo/blob/9.0/addons/account/models/account_invoice.py#L487 si asigna sin alguna discriminacion.

**Comment by ovnicraft** [comment]
He revisado en una instalacion limpia y funciona correcto, asigna el contribuyente en ambos casos: proveedor y cliente.

**Comment by ocurieles** [comment]
Yo tambien lo probe en instalación Limpia y mira.

![test1](https://cloud.githubusercontent.com/assets/16121174/17789407/b5fa990c-6557-11e6-90cb-c3cbbc02997d.png)
![test2](https://cloud.githubusercontent.com/assets/16121174/17789409/b81eadd6-6557-11e6-90f1-8610d59cbe91.png)

**Comment by ovnicraft** [comment]
Puedes de pronto revisar que tengas la ultima revisión git y con eso probar.

**Comment by ovnicraft** [comment]
Te recomiendo usar solo el account y probar, parece que es otro modulo que introduce el bug.

**Comment by ocurieles** [comment]
solo tengo Partner y retenciones

**Comment by ovnicraft** [comment]
En la pestaña de partner que nos envias estan varios botones de CRM, ventas, agenda posiblemente uno de estos introduce el erro.

**Comment by ocurieles** [comment]
Cree una base nueva, solo instale el modulo Accounting y el módulo de Partner del Ecuador y ahora no me despliega los fiscal Position, al instalar el módulo de retenciones obtengo este error:

Odoo Server Error
Traceback (most recent call last):
  File "/home/ocurieles/desarrollo/sources/odoo9/odoo9/openerp/http.py", line 647, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/ocurieles/desarrollo/sources/odoo9/odoo9/openerp/http.py", line 684, in dispatch
    result = self._call_function(*_self.params)
  File "/home/ocurieles/desarrollo/sources/odoo9/odoo9/openerp/http.py", line 320, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/home/ocurieles/desarrollo/sources/odoo9/odoo9/openerp/service/model.py", line 118, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/home/ocurieles/desarrollo/sources/odoo9/odoo9/openerp/http.py", line 313, in checked_call
    result = self.endpoint(_a, *_kw)
  File "/home/ocurieles/desarrollo/sources/odoo9/odoo9/openerp/http.py", line 963, in __call__
    return self.method(_args, *_kw)
  File "/home/ocurieles/desarrollo/sources/odoo9/odoo9/openerp/http.py", line 513, in response_wrap
    response = f(_args, *_kw)
  File "/home/ocurieles/desarrollo/sources/odoo9/odoo9/addons/web/controllers/main.py", line 901, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/ocurieles/desarrollo/sources/odoo9/odoo9/addons/web/controllers/main.py", line 889, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, _args, *_kwargs)
  File "/home/ocurieles/desarrollo/sources/odoo9/odoo9/openerp/api.py", line 250, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/ocurieles/desarrollo/sources/odoo9/odoo9/openerp/addons/base/module/module.py", line 459, in button_immediate_install
    return self._button_immediate_function(cr, uid, ids, self.button_install, context=context)
  File "/home/ocurieles/desarrollo/sources/odoo9/odoo9/openerp/api.py", line 250, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/ocurieles/desarrollo/sources/odoo9/odoo9/openerp/addons/base/module/module.py", line 533, in _button_immediate_function
    registry = openerp.modules.registry.RegistryManager.new(cr.dbname, update_module=True)
  File "/home/ocurieles/desarrollo/sources/odoo9/odoo9/openerp/modules/registry.py", line 386, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/ocurieles/desarrollo/sources/odoo9/odoo9/openerp/modules/loading.py", line 338, in load_modules
    loaded_modules, update_module)
  File "/home/ocurieles/desarrollo/sources/odoo9/odoo9/openerp/modules/loading.py", line 237, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/home/ocurieles/desarrollo/sources/odoo9/odoo9/openerp/modules/loading.py", line 156, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/home/ocurieles/desarrollo/sources/odoo9/odoo9/openerp/modules/loading.py", line 98, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/home/ocurieles/desarrollo/sources/odoo9/odoo9/openerp/tools/convert.py", line 851, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/home/ocurieles/desarrollo/sources/odoo9/odoo9/openerp/tools/convert.py", line 938, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/home/ocurieles/desarrollo/sources/odoo9/odoo9/openerp/tools/convert.py", line 801, in parse
    self.parse(rec, mode)
  File "/home/ocurieles/desarrollo/sources/odoo9/odoo9/openerp/tools/convert.py", line 804, in parse
    self._tags[rec.tag](self.cr, rec, de, mode=mode)
  File "/home/ocurieles/desarrollo/sources/odoo9/odoo9/openerp/tools/convert.py", line 708, in _tag_record
    id = self.pool['ir.model.data']._update(cr, self.uid, rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode, context=rec_context )
  File "/home/ocurieles/desarrollo/sources/odoo9/odoo9/openerp/api.py", line 250, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/ocurieles/desarrollo/sources/odoo9/odoo9/openerp/addons/base/ir/ir_model.py", line 1143, in _update
    res_id = model_obj.create(cr, uid, values, context=context)
  File "/home/ocurieles/desarrollo/sources/odoo9/odoo9/openerp/api.py", line 250, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/ocurieles/desarrollo/sources/odoo9/odoo9/openerp/addons/base/ir/ir_ui_view.py", line 353, in create
    context=context)
  File "/home/ocurieles/desarrollo/sources/odoo9/odoo9/openerp/api.py", line 250, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/ocurieles/desarrollo/sources/odoo9/odoo9/openerp/api.py", line 354, in old_api
    result = method(recs, _args, *_kwargs)
  File "/home/ocurieles/desarrollo/sources/odoo9/odoo9/openerp/models.py", line 4157, in create
    record = self.browse(self._create(old_vals))
  File "/home/ocurieles/desarrollo/sources/odoo9/odoo9/openerp/api.py", line 248, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/home/ocurieles/desarrollo/sources/odoo9/odoo9/openerp/api.py", line 490, in new_api
    result = method(self._model, cr, uid, _args, *_old_kwargs)
  File "/home/ocurieles/desarrollo/sources/odoo9/odoo9/openerp/models.py", line 4354, in _create
    recs._validate_fields(vals)
  File "/home/ocurieles/desarrollo/sources/odoo9/odoo9/openerp/api.py", line 248, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/home/ocurieles/desarrollo/sources/odoo9/odoo9/openerp/models.py", line 1271, in _validate_fields
    raise ValidationError('\n'.join(errors))
ParseError: "Invalid view definition

Error details:
Field `has_retention` does not exist

Error context:
View `account.invoice.authinv.form`
[view_id: 491, xml_id: n/a, model: account.invoice, parent_id: 399]
None" while parsing /home/ocurieles/desarrollo/sources/odoo9/odoo-ecuador/l10n_ec_withholding/views/withholding_view.xml:30, near
<record id="view_retention_authinv_form" model="ir.ui.view">
            <field name="name">account.invoice.authinv.form</field>
            <field name="model">account.invoice</field>
            <field name="inherit_id" ref="account.invoice_supplier_form"/>
            <field name="arch" type="xml">
                <data><xpath expr="//field[@name='move_id']" position="after">
                    <field name="retention_id"/>
                </xpath>
                <xpath expr="//field[@name='fiscal_position_id']" position="attributes">
                    <attribute name="required">1</attribute>
                </xpath>
                <xpath expr="//field[@name='date_due']" position="after">
                    <label string="Nro. de Retenci&#243;n" for="withdrawing_number" attrs="{'invisible': [('has_retention','=',False)]}"/>
                    <div attrs="{'invisible': [('has_retention','=',False)]}">
                        <field name="create_retention_type" class="oe_inline"/>
                        <field name="withholding_number" class="oe_inline" attrs="{'invisible': [('create_retention_type','=','auto')]}"/>
                        <field name="sustento_id" placeholder="Sustento" required="1" widget="selection" class="oe_inline oe_edit_only"/>
                    </div>
                    <field name="has_retention" invisible="1"/>
                </xpath>

```
            <xpath expr="//field[@name='date_invoice']" position="attributes">
                <attribute name="required">1</attribute>
            </xpath>
            <xpath expr="//field[@name='partner_id']" position="attributes">
                <attribute name="string">Proveedor</attribute>
            </xpath>
            <xpath expr="//field[@name='amount_total']" position="replace">
                <field name="amount_pay" string="Total" class="oe_subtotal_footer_separator" widget="monetary" options="{'currency_field': 'currency_id'}"/>
                <field name="amount_tax_retention"/>
                <field name="amount_total" string="Total a Pagar" class="oe_subtotal_footer_separator" widget="monetary" options="{'currency_field': 'currency_id'}"/>
            </xpath>
            <xpath expr="//button[@name='invoice_open'][last()]" position="after">
                <button name="print_retention" string="Retenci&#243;n" type="object" states="open" icon="gtk-print"/>
                <button name="print_move" string="Comprobante" type="object" states="open,paid" icon="gtk-print"/>
            </xpath>
        </data></field>
    </record>
```

**Comment by ovnicraft** [comment]
@ocurieles puedes abrir un issue especifico con este error.

**Comment by ocurieles** [comment]
Probe en la nueva instalación y en factura de compras efectivamente coloca el Fiscal Position automaticamente pero en las de ventas no.

Saludos
