### ISSUE TITLE
Odoo Error install  Partner for Ecuador Module -   sql_db.py  IF NOT EXIST  

### ISSUE THREAD

**Issue by ronnbar2011** [odoo-ecuador/odoo-ecuador#175]
Sobre Odoo 10
Instalado en ambiente Linux Fedora.
Base de datos PostgreSQL

Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/odoo/http.py", line 638, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/site-packages/odoo/http.py", line 675, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python2.7/site-packages/odoo/http.py", line 331, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/odoo/service/model.py", line 119, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/odoo/http.py", line 324, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python2.7/site-packages/odoo/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python2.7/site-packages/odoo/http.py", line 504, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python2.7/site-packages/odoo/addons/web/controllers/main.py", line 866, in call_button
    action = self._call_kw(model, method, args, {})
  File "/usr/lib/python2.7/site-packages/odoo/addons/web/controllers/main.py", line 854, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python2.7/site-packages/odoo/api.py", line 681, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python2.7/site-packages/odoo/api.py", line 672, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/odoo/addons/base/module/module.py", line 410, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/usr/lib/python2.7/site-packages/odoo/addons/base/module/module.py", line 484, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/usr/lib/python2.7/site-packages/odoo/modules/registry.py", line 78, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/usr/lib/python2.7/site-packages/odoo/modules/loading.py", line 339, in load_modules
    loaded_modules, update_module)
  File "/usr/lib/python2.7/site-packages/odoo/modules/loading.py", line 237, in load_marked_modules
loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/usr/lib/python2.7/site-packages/odoo/modules/loading.py", line 136, in load_module_graph
    registry.init_models(cr, model_names, {'module': package.name})
  File "/usr/lib/python2.7/site-packages/odoo/modules/registry.py", line 316, in init_models
    model.init()
  File "/usr/lib/python2.7/site-packages/odoo/addons/l10n_ec_partner/models/partner.py", line 34, in init
    self._cr.execute(sql_index)
  File "/usr/lib/python2.7/site-packages/odoo/sql_db.py", line 141, in wrapper
    return f(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/odoo/sql_db.py", line 218, in execute
    res = self._obj.execute(query, params)
ProgrammingError: error de sintaxis en o cerca de «NOT»
LINE 2:         CREATE UNIQUE INDEX IF NOT EXISTS

La sintaxis de PostgreSQL no permite  "IF NOT EXIST" en la creacion de un Indice.

**Comment by ovnicraft** [comment]
@ronnbar2011 debemos hacer una aclaracion sobre eso, es un requerimiento usar pg>=9.5
