### ISSUE TITLE
Problemas al crear compañia

### ISSUE THREAD

**Issue by efirvida** [odoo-ecuador/odoo-ecuador#192]
Cuando trato de crear una nueva compañia me sale este error

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 638, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 675, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 331, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/service/model.py", line 119, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 324, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 504, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/web/controllers/main.py", line 862, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/web/controllers/main.py", line 854, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/api.py", line 681, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/api.py", line 672, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/models.py", line 5416, in onchange
    record = self.new(values)
  File "/usr/lib/python2.7/dist-packages/odoo/models.py", line 4993, in new
    record._cache.update(record._convert_to_cache(values, update=True))
  File "/usr/lib/python2.7/dist-packages/odoo/models.py", line 4872, in _convert_to_cache
    for name, value in values.iteritems()
  File "/usr/lib/python2.7/dist-packages/odoo/models.py", line 4873, in <dictcomp>
    if name in fields
  File "/usr/lib/python2.7/dist-packages/odoo/fields.py", line 1712, in convert_to_cache
    raise ValueError("Wrong value for %s: %r" % (self, value))
ValueError: Wrong value for res.company.emission_code: 1
```

Luego no me deja crearla de ninguna forma diciendo:
```

The operation cannot be completed, probably due to the following:
- deletion: you may be trying to delete a record while other records still reference it
- creation/update: a mandatory field is not correctly set

[object with reference: identifier - identifier]
```

**Comment by ovnicraft** [comment]
@efirvida que modulos de este repo tienes instalados ?

**Comment by ovnicraft** [comment]
Cierro el issue por abandono.
