### ISSUE TITLE
Por Favor ayuda - Error en Comprobantes Electrónicos

### ISSUE THREAD

**Issue by AizenL** [odoo-ecuador/odoo-ecuador#200]
Saludos, y muchas gracias por aportar a la comunidad Ecuatoriana, estoy intentando probar la emisión de comprobantes electrónicos y me da el siguiente error.
Tengo configurado el path de la firma asi: "C:\Program Files (x86)\Odoo 8.0-20170327\server\openerp\addons\l10n_ec_einvoice\xades\firma.p12" No se si es correcto.

`Traceback (most recent call last):
  File "C:\Program Files (x86)\Odoo 8.0-20170327\server\.\openerp\http.py", line 544, in _handle_exception
  File "C:\Program Files (x86)\Odoo 8.0-20170327\server\.\openerp\http.py", line 581, in dispatch
  File "C:\Program Files (x86)\Odoo 8.0-20170327\server\.\openerp\http.py", line 317, in _call_function
  File "C:\Program Files (x86)\Odoo 8.0-20170327\server\.\openerp\service\model.py", line 118, in wrapper
  File "C:\Program Files (x86)\Odoo 8.0-20170327\server\.\openerp\http.py", line 314, in checked_call
  File "C:\Program Files (x86)\Odoo 8.0-20170327\server\.\openerp\http.py", line 810, in __call__
  File "C:\Program Files (x86)\Odoo 8.0-20170327\server\.\openerp\http.py", line 410, in response_wrap
  File "C:\Program Files (x86)\Odoo 8.0-20170327\server\openerp\addons\web\controllers\main.py", line 948, in call_button
  File "C:\Program Files (x86)\Odoo 8.0-20170327\server\openerp\addons\web\controllers\main.py", line 936, in _call_kw
  File "C:\Program Files (x86)\Odoo 8.0-20170327\server\.\openerp\api.py", line 268, in wrapper
  File "C:\Program Files (x86)\Odoo 8.0-20170327\server\.\openerp\api.py", line 399, in old_api
  File "C:\Program Files (x86)\Odoo 8.0-20170327\server\openerp\addons\l10n_ec_einvoice\einvoice.py", line 151, in action_generate_einvoice
  File "C:\Program Files (x86)\Odoo 8.0-20170327\server\openerp\addons\l10n_ec_einvoice\xades\xades.py", line 71, in sign
TypeError: exceptions must be old-style classes or derived from BaseException, not int`

**Comment by AizenL** [comment]
Saludos estoy recibiendo este error 39 FIRMA INVALIDA ERROR No se pudo convertir en Certificado X509

**Comment by ovnicraft** [comment]
Puedes describir los pasos para obtener ese error ?

**Comment by AizenL** [comment]
Saludos e instalado desde cero, Odoo version 8 y la localización Ecuatoriana, ya configure el path al certificado y la clave de la firma, en este momento estoy recibiendo el siguiente error: 
` File "C:\Program Files (x86)\Odoo 8.0-20170327\server\openerp\addons\l10n_ec_einvoice\einvoice.py", line 152, in action_generate_einvoice
  File "C:\Program Files (x86)\Odoo 8.0-20170327\server\openerp\addons\l10n_ec_einvoice\xades\sri.py", line 78, in send_receipt
AttributeError: respuestaSolicitud instance has no attribute 'estado'`

Por favor tu ayuda o alguna guia.

**Comment by AizenL** [comment]
Saludos talvez trabajas como Freelance no sé si puedas ayudarme unas horas a configurar esto.

**Comment by ovnicraft** [comment]
Enviame un mail a cs@prisehub.om

**Comment by jmarcatoma** [comment]
me podrías ayudar tengo el mismo error
