### ISSUE TITLE
Errores instalando localización en Odoo v11

### ISSUE THREAD

**Issue by rlguerrero888** [odoo-ecuador/odoo-ecuador#210]
Hola,
En Odoo 11 no pude instalar los siguientes módulos:

- Establecimientos y autorizaciones del SRI
- Impresion de Cheques para Ecuador
- Electronic Documents for Ecuador
- Manage Employee Contracts for Ecuador
- Partner for Ecuador

Arrojó el siguiente error:
Imposible instalar el módulo "l10n_ec_partner" porqué hay una dependencia externa no resuelta: No module named stdnum

**Comment by rlguerrero888** [comment]
Hola,
En otros módulos me aparecieron errores similares al siguiente:
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/tools/convert.py", line 741, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/odoo/odoo-server/odoo/tools/convert.py", line 338, in _tag_function
    _eval_xml(self, rec, env)
  File "/odoo/odoo-server/odoo/tools/convert.py", line 191, in _eval_xml
    model = env[node.get('model')]
  File "/odoo/odoo-server/odoo/api.py", line 760, in __getitem__
    return self.registry[model_name]._browse((), self)
  File "/odoo/odoo-server/odoo/modules/registry.py", line 181, in __getitem__
    return self.models[model_name]
KeyError: 'ir.values'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/http.py", line 646, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/odoo/odoo-server/odoo/http.py", line 307, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/odoo/odoo-server/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/odoo/odoo-server/odoo/http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "/odoo/odoo-server/odoo/http.py", line 339, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/odoo/odoo-server/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/odoo/odoo-server/odoo/http.py", line 332, in checked_call
    result = self.endpoint(*a, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 927, in __call__
    return self.method(*args, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 512, in response_wrap
    response = f(*args, **kw)
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 928, in call_button
    action = self._call_kw(model, method, args, {})
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 916, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/odoo/odoo-server/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/odoo/odoo-server/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-39>", line 2, in button_immediate_install
  File "/odoo/odoo-server/odoo/addons/base/module/module.py", line 71, in check_and_log
    return method(self, *args, **kwargs)
  File "/odoo/odoo-server/odoo/addons/base/module/module.py", line 448, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/odoo/odoo-server/odoo/addons/base/module/module.py", line 541, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/odoo/odoo-server/odoo/modules/registry.py", line 85, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/odoo/odoo-server/odoo/modules/loading.py", line 343, in load_modules
    loaded_modules, update_module)
  File "/odoo/odoo-server/odoo/modules/loading.py", line 242, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/odoo/odoo-server/odoo/modules/loading.py", line 156, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/odoo/odoo-server/odoo/modules/loading.py", line 94, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/odoo/odoo-server/odoo/tools/convert.py", line 788, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/odoo/odoo-server/odoo/tools/convert.py", line 849, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/odoo/odoo-server/odoo/tools/convert.py", line 738, in parse
    self.parse(rec, mode)
  File "/odoo/odoo-server/odoo/tools/convert.py", line 748, in parse
    exc_info[2]
  File "/odoo/odoo-server/odoo/tools/pycompat.py", line 86, in reraise
    raise value.with_traceback(tb)
  File "/odoo/odoo-server/odoo/tools/convert.py", line 741, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/odoo/odoo-server/odoo/tools/convert.py", line 338, in _tag_function
    _eval_xml(self, rec, env)
  File "/odoo/odoo-server/odoo/tools/convert.py", line 191, in _eval_xml
    model = env[node.get('model')]
  File "/odoo/odoo-server/odoo/api.py", line 760, in __getitem__
    return self.registry[model_name]._browse((), self)
  File "/odoo/odoo-server/odoo/modules/registry.py", line 181, in __getitem__
    return self.models[model_name]
odoo.tools.convert.ParseError: "ir.values" while parsing /odoo/custom/odoo-ecuador/l10n_ec_chart/data/account_chart.xml:3133, near
<function id="partner_account_receivable_default_set" model="ir.values" name="set_default" eval="('res.partner', 'property_account_receivable_id', ref('101020601'))"/>

**Comment by ocurieles** [comment]
Hola - En Odoo 11 eliminaron el módulo de contabilidad, por ende asumo que no se podrá instalar nada de esto.
Saludos.

**Comment by ovnicraft** [comment]
@rlguerrero888 no es instalable de pronto por la version, no hecho ninguna prueba, la migración de los modulos empezaremos en segunda semana de enero.

La libreria python-stdnum es requierida para la instalación

@ocurieles el motor sigue en el core, por cuanto debe funcionar

**Comment by rlguerrero888** [comment]
gracias @ocurieles y @ovnicraft
