### ISSUE TITLE
Error al Crear Factura en POS

### ISSUE THREAD

**Issue by jmurillo77** [odoo-ecuador/odoo-ecuador#211]
Saludos, Tengo el siguiente error:

Traceback (most recent call last):
  File "/opt/bitnami/apps/odoo/lib/odoo-10.0.post20170815-py2.7.egg/odoo/http.py", line 640, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/bitnami/apps/odoo/lib/odoo-10.0.post20170815-py2.7.egg/odoo/http.py", line 677, in dispatch
    result = self._call_function(**self.params)
  File "/opt/bitnami/apps/odoo/lib/odoo-10.0.post20170815-py2.7.egg/odoo/http.py", line 333, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-10.0.post20170815-py2.7.egg/odoo/service/model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-10.0.post20170815-py2.7.egg/odoo/http.py", line 326, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/bitnami/apps/odoo/lib/odoo-10.0.post20170815-py2.7.egg/odoo/http.py", line 935, in __call__
    return self.method(*args, **kw)
  File "/opt/bitnami/apps/odoo/lib/odoo-10.0.post20170815-py2.7.egg/odoo/http.py", line 506, in response_wrap
    response = f(*args, **kw)
  File "/opt/bitnami/apps/odoo/lib/odoo-10.0.post20170815-py2.7.egg/odoo/addons/web/controllers/main.py", line 885, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-10.0.post20170815-py2.7.egg/odoo/addons/web/controllers/main.py", line 877, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-10.0.post20170815-py2.7.egg/odoo/api.py", line 679, in call_kw
    return call_kw_model(method, model, args, kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-10.0.post20170815-py2.7.egg/odoo/api.py", line 664, in call_kw_model
    result = method(recs, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-10.0.post20170815-py2.7.egg/odoo/addons/point_of_sale/models/pos_order.py", line 563, in create_from_ui
    pos_order.action_pos_order_invoice()
  File "/opt/bitnami/apps/odoo/lib/odoo-10.0.post20170815-py2.7.egg/odoo/addons/l10n_ec_pos/models/order.py", line 21, in action_pos_order_invoice
    order.invoice_id and order.invoice_id.action_invoice_open()
  File "/opt/bitnami/apps/odoo/lib/odoo-10.0.post20170815-py2.7.egg/odoo/addons/l10n_ec_picking_invoice/models/invoice.py", line 56, in action_invoice_open
    to_open_invoices.action_number()
  File "/opt/bitnami/apps/odoo/lib/odoo-10.0.post20170815-py2.7.egg/odoo/addons/l10n_ec_authorisation/models/authorisation.py", line 347, in action_number
    number = sequence.next_by_id()
  File "/opt/bitnami/apps/odoo/lib/odoo-10.0.post20170815-py2.7.egg/odoo/addons/base/ir/ir_sequence.py", line 232, in next_by_id
    return self._next()
  File "/opt/bitnami/apps/odoo/lib/odoo-10.0.post20170815-py2.7.egg/odoo/addons/base/ir/ir_sequence.py", line 218, in _next
    return self._next_do()
  File "/opt/bitnami/apps/odoo/lib/odoo-10.0.post20170815-py2.7.egg/odoo/addons/base/ir/ir_sequence.py", line 162, in _next_do
    number_next = _update_nogap(self, self.number_increment)
  File "/opt/bitnami/apps/odoo/lib/odoo-10.0.post20170815-py2.7.egg/odoo/addons/base/ir/ir_sequence.py", line 52, in _update_nogap
    self._cr.execute("SELECT number_next FROM %s WHERE id=%s FOR UPDATE NOWAIT" % (self._table, self.id))
  File "/opt/bitnami/apps/odoo/lib/odoo-10.0.post20170815-py2.7.egg/odoo/sql_db.py", line 154, in wrapper
    return f(self, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-10.0.post20170815-py2.7.egg/odoo/sql_db.py", line 231, in execute
    res = self._obj.execute(query, params)
ProgrammingError: operator does not exist: integer = boolean
LINE 1: SELECT number_next FROM ir_sequence WHERE id=False FOR UPDAT...
                                                    ^
HINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts.

Esto es al momento de hacer una factura por el POS.

**Comment by Manzarena** [comment]
Buen día, también tengo el mismo error aun cuando agregue una secuencia en el diario del pos.

**Comment by ovnicraft** [comment]
Esta configurada la autorizacion en el diario de ventas ?

**Comment by Manzarena** [comment]
Se donde se configura el diario de venta en el modulo de contabilidad para las facturas de clientes, pero en el pos nose como hacerlo. Ademas que entendería que son dos diarios de venta diferentes:
1.- POS Sale Journal 
2.- Facturas de Clientes

Cuando creo la autorización, también se crea un secuencial y al ver las facturas me muestra con dos numeraciones.

**Comment by ovnicraft** [comment]
Cada POS tiene un diario de ventas asignado, en ese diario de ventas debes asignar una autorizacion.
Respecto a que se ven dos numeraciones, la una es el numero de factura y el otro el numero de asiento.

Para EC  es requerido el numero de factura.

**Comment by Manzarena** [comment]
Eso veo que me muestra 001001000000001INV/2018/0001, pero al intentar crear el documento electrónico me sale errores.

Pero como hago en el pos con este error LINE 1: SELECT number_next FROM ir_sequence WHERE id=False FOR UPDAT...
porque entenderia que seria otro secuencial para el POS???? me refiero por el el punto de emision.

**Comment by ovnicraft** [comment]
Puedes confirmar si en el POS sale journal tienes la autorizacion configurada  ?

**Comment by Manzarena** [comment]
Buenas noches,
Si tengo asignada la autorización en el diario del pos. Pero aún así me
sale ese error.

**Comment by jmurillo77** [comment]
Para que se tenga una referencia, yo estoy trabajando sobre un servidor virtual de Amazon, Bitnami
Sistema Operativo: Ubuntu
Versión de Odoo: 10

**Comment by ceduardodch** [comment]
Tengo el mismo error si tienen alguna solucion o comentario estaria agradecido

**Comment by phoenixgus87** [comment]
Deben cambiar el metodo action_number definido en el addon l10n_ec_authorisation por el lo siguiente:

@api.multi
    def action_number(self):
        # TODO: ver donde incluir el metodo de numeracion
        #self.ensure_one()
        if self.type not in ['out_invoice', 'liq_purchase', 'out_refund']:
            return
        number = self.internal_inv_number
        if not self.auth_inv_id:
            # asegura la autorizacion en el objeto
            self._onchange_partner_id()
        if not number:
            self.auth_inv_id = self.journal_id.auth_out_invoice_id
            sequence = self.journal_id.auth_out_invoice_id.sequence_id
            number = sequence.next_by_id()
        self.write({'reference': number, 'internal_inv_number': number})

**Comment by ovnicraft** [comment]
@phoenixgus87 puedes crear un PR para corregir el error ?
