### ISSUE TITLE
[10.0] Field `ambiente` does not exist

### ISSUE THREAD

**Issue by abdufarag** [odoo-ecuador/odoo-ecuador#233]
Al crear la factura de venta me sale este error.

```
Traceback (most recent call last):
  File "/opt/bitnami/apps/odoo/lib/odoo-10.0.post20180218-py2.7.egg/odoo/http.py", line 641, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/bitnami/apps/odoo/lib/odoo-10.0.post20180218-py2.7.egg/odoo/http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "/opt/bitnami/apps/odoo/lib/odoo-10.0.post20180218-py2.7.egg/odoo/http.py", line 333, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-10.0.post20180218-py2.7.egg/odoo/service/model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-10.0.post20180218-py2.7.egg/odoo/http.py", line 326, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/bitnami/apps/odoo/lib/odoo-10.0.post20180218-py2.7.egg/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/opt/bitnami/apps/odoo/lib/odoo-10.0.post20180218-py2.7.egg/odoo/http.py", line 506, in response_wrap
    response = f(*args, **kw)
  File "/opt/bitnami/apps/odoo/lib/odoo-10.0.post20180218-py2.7.egg/odoo/addons/web/controllers/main.py", line 890, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-10.0.post20180218-py2.7.egg/odoo/addons/web/controllers/main.py", line 882, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-10.0.post20180218-py2.7.egg/odoo/api.py", line 687, in call_kw
    return call_kw_model(method, model, args, kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-10.0.post20180218-py2.7.egg/odoo/api.py", line 672, in call_kw_model
    result = method(recs, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-10.0.post20180218-py2.7.egg/odoo/models.py", line 1334, in load_views
    for [v_id, v_type] in views
  File "/opt/bitnami/apps/odoo/lib/odoo-10.0.post20180218-py2.7.egg/odoo/models.py", line 1334, in <dictcomp>
    for [v_id, v_type] in views
  File "/opt/bitnami/apps/odoo/lib/odoo-10.0.post20180218-py2.7.egg/odoo/addons/account/models/account_invoice.py", line 386, in fields_view_get
    return super(AccountInvoice, self).fields_view_get(view_id=view_id, view_type=view_type, toolbar=toolbar, submenu=submenu)
  File "/opt/bitnami/apps/odoo/lib/odoo-10.0.post20180218-py2.7.egg/odoo/addons/mail/models/mail_thread.py", line 362, in fields_view_get
    res = super(MailThread, self).fields_view_get(view_id=view_id, view_type=view_type, toolbar=toolbar, submenu=submenu)
  File "/opt/bitnami/apps/odoo/lib/odoo-10.0.post20180218-py2.7.egg/odoo/models.py", line 1413, in fields_view_get
    xarch, xfields = View.postprocess_and_fields(self._name, etree.fromstring(result['arch']), view_id)
  File "/opt/bitnami/apps/odoo/lib/odoo-10.0.post20180218-py2.7.egg/odoo/addons/base/ir/ir_ui_view.py", line 910, in postprocess_and_fields
    self.raise_view_error(message, view_id)
  File "/opt/bitnami/apps/odoo/lib/odoo-10.0.post20180218-py2.7.egg/odoo/addons/base/ir/ir_ui_view.py", line 468, in raise_view_error
    raise ValueError(message)
ValueError: Field `ambiente` does not exist

Error context:
View `account.invoice.form`
[view_id: 501, xml_id: account.invoice_form, model: account.invoice, parent_id: n/a]
```

**Comment by ovnicraft** [comment]
@abdufarag que modulos instalados ?
