### ISSUE TITLE
Error al tratar de Generar Doc. Electrónico

### ISSUE THREAD

**Issue by lakerjc1979** [odoo-ecuador/odoo-ecuador#251]
Buenas con todos, tengo el siguiente problema al intentar generar el documento electrónico:

Traceback (most recent call last):
  File "/opt/odoo/odoo/http.py", line 642, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo/http.py", line 684, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odoo/http.py", line 334, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo/service/model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo/http.py", line 327, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/odoo/http.py", line 942, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo/http.py", line 507, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/addons/web/controllers/main.py", line 899, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/addons/web/controllers/main.py", line 887, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/extra-addons/l10n_ec_einvoice/models/einvoice.py", line 192, in action_generate_einvoice
    ok, errores = inv_xml.send_receipt(signed_document)
  File "/opt/extra-addons/l10n_ec_einvoice/xades/sri.py", line 78, in send_receipt
    self.logger.info('Estado de respuesta documento: %s' % result.estado)
AttributeError: 'respuestaSolicitud' object has no attribute 'estado'

Espero me puedan ayudar, de antemano agradezco sus comentarios, saludos.

**Comment by r1cheX** [comment]
Igual me sale, lo podiste resolver amigo @lakerjc1979 ?
