### ISSUE TITLE
Error al imprimir comprobante contable

### ISSUE THREAD

**Issue by ovnicraft** [odoo-ecuador/odoo-ecuador#41]
El error al dar clic en el boton de comprobante contable:
Traceback (most recent call last):
  File "/Users/ovnicraft/development/odoo/openerp/service/web_services.py", line 711, in go
    obj = netsvc.LocalService('report.'+object)
  File "/Users/ovnicraft/development/odoo/openerp/netsvc.py", line 98, in LocalService
    return Service._services[name]
KeyError: u'report.report_move'
2015-01-04 07:24:21,318 24443 ERROR eia openerp.netsvc: report.report_move
(<type 'exceptions.KeyError'>, KeyError(u'report.report_move',), <traceback object at 0x10f5ba128>)
Traceback (most recent call last):
  File "/Users/ovnicraft/development/odoo/openerp/netsvc.py", line 296, in dispatch_rpc
    result = ExportService.getService(service_name).dispatch(method, params)
  File "/Users/ovnicraft/development/odoo/openerp/service/web_services.py", line 654, in dispatch
    res = fn(db, uid, *params)
  File "/Users/ovnicraft/development/odoo/openerp/service/web_services.py", line 760, in exp_report_get
    return self._check_report(report_id)
  File "/Users/ovnicraft/development/odoo/openerp/service/web_services.py", line 738, in _check_report
    netsvc.abort_response(exc, exc.message, 'warning', exc.traceback)
  File "/Users/ovnicraft/development/odoo/openerp/netsvc.py", line 71, in abort_response
    raise openerp.osv.osv.except_osv(description, details)
except_osv: (u'report.report_move', (<type 'exceptions.KeyError'>, KeyError(u'report.report_move',), <traceback object at 0x10f5ba128>))
2015-01-04 07:24:21,349 24443 INFO eia werkzeug: 127.0.0.1 - - [04/Jan/2015 07:24:21] "POST /web/report HTTP/1.1" 500 -

**Comment by ovnicraft** [comment]
Se elimino el reporte mako para dar paso al qweb
