### ISSUE TITLE
Error de instalacion en 8.0

### ISSUE THREAD

**Issue by ovnicraft** [odoo-ecuador/odoo-ecuador#46]
Traceback (most recent call last):
  File "/opt/odoo/openerp/http.py", line 524, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/openerp/http.py", line 545, in dispatch
    result = self._call_function(*_self.params)
  File "/opt/odoo/openerp/http.py", line 301, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/opt/odoo/openerp/service/model.py", line 113, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/opt/odoo/openerp/http.py", line 298, in checked_call
    return self.endpoint(_a, *_kw)
  File "/opt/odoo/openerp/http.py", line 761, in __call__
    return self.method(_args, *_kw)
  File "/opt/odoo/openerp/http.py", line 394, in response_wrap
    response = f(_args, *_kw)
  File "/opt/odoo/addons/web/controllers/main.py", line 953, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/addons/web/controllers/main.py", line 941, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr,
request.uid, _args, *_kwargs)
  File "/opt/odoo/openerp/api.py", line 237, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/openerp/addons/base/module/module.py", line 450, in
button_immediate_install
    return self._button_immediate_function(cr, uid, ids,
self.button_install, context=context)
  File "/opt/odoo/openerp/api.py", line 237, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/openerp/addons/base/module/module.py", line 498, in
_button_immediate_function
    registry = openerp.modules.registry.RegistryManager.new(cr.dbname,
update_module=True)
  File "/opt/odoo/openerp/modules/registry.py", line 346, in new
    openerp.modules.load_modules(registry._db, force_demo, status,
update_module)
  File "/opt/odoo/openerp/modules/loading.py", line 363, in load_modules
    loaded_modules, update_module)
  File "/opt/odoo/openerp/modules/loading.py", line 263, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict,
report=report, skip_modules=loaded_modules,
perform_checks=perform_checks)
  File "/opt/odoo/openerp/modules/loading.py", line 182, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/opt/odoo/openerp/modules/loading.py", line 118, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode,
noupdate, kind, report)
  File "/opt/odoo/openerp/tools/convert.py", line 901, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/opt/odoo/openerp/tools/convert.py", line 987, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/opt/odoo/openerp/tools/convert.py", line 853, in parse
    self._tags[rec.tag](self.cr, rec, n, mode=mode)
  File "/opt/odoo/openerp/tools/convert.py", line 763, in _tag_record
    id = self.pool['ir.model.data']._update(cr, self.uid, rec_model,
self.module, res, rec_id or False, not self.isnoupdate(data_node),
noupdate=self.isnoupdate(data_node), mode=self.mode,
context=rec_context )
  File "/opt/odoo/openerp/api.py", line 237, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/openerp/addons/base/ir/ir_model.py", line 1067, in _update
    res_id = model_obj.create(cr, uid, values, context=context)
  File "/opt/odoo/openerp/api.py", line 237, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/openerp/addons/base/ir/ir_ui_view.py", line 264, in create
    context=context)
  File "/opt/odoo/openerp/api.py", line 237, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/openerp/api.py", line 332, in old_api
    result = method(recs, _args, *_kwargs)
  File "/opt/odoo/openerp/models.py", line 4007, in create
    record = self.browse(self._create(old_vals))
  File "/opt/odoo/openerp/api.py", line 235, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/opt/odoo/openerp/api.py", line 464, in new_api
    result = method(self._model, cr, uid, _args, *_kwargs)
  File "/opt/odoo/openerp/models.py", line 4127, in _create
    self._check_selection_field_value(cr, user, field, vals[field],
context=context)
  File "/opt/odoo/openerp/api.py", line 237, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/openerp/api.py", line 332, in old_api
    result = method(recs, _args, *_kwargs)
  File "/opt/odoo/openerp/models.py", line 2259, in _check_selection_field_value
    field.convert_to_cache(value, self)
  File "/opt/odoo/openerp/fields.py", line 1324, in convert_to_cache
    raise ValueError("Wrong value for %s: %r" % (self, value))
ParseError: "Wrong value for ir.ui.view.type: 'xpath'" while parsing
/opt/odoo-ec/l10n_ec_partner/view/partner_view.xml:21, near
<record id="view_partner2_tree" model="ir.ui.view">
  <field name="name">view.partner.tree2</field>
  <field name="model">res.partner</field>
  <field name="arch" type="xml">
    <xpath expr="/tree/field[@name='name']" position="before">
    <field name="ced_ruc"/>
  </xpath>
  </field>
</record>

**Comment by celm1990** [comment]
Falta la vista de la que se hereda
<field name="inherit_id" ref="base.view_partner_tree"/>

**Comment by ayepezv** [comment]
A querer efectuar el agregar los add me arroja el siguiente error y no se agregan:
andres@ubuntu-OpenErp:/opt/odoo/server$ ./openerp-server --addons-path=openerp/addons,openerp/odoo-ecuador
2015-10-07 17:07:48,515 6999 INFO ? openerp: OpenERP version 8.0-20150920
2015-10-07 17:07:48,519 6999 INFO ? openerp: addons paths: ['/home/andres/.local/share/Odoo/addons/8.0', u'/opt/odoo/server/openerp/addons', u'/opt/odoo/server/openerp/odoo-ecuador']
2015-10-07 17:07:48,520 6999 INFO ? openerp: database hostname: localhost
2015-10-07 17:07:48,521 6999 INFO ? openerp: database port: 5432
2015-10-07 17:07:48,521 6999 INFO ? openerp: database user: andres
2015-10-07 17:07:50,669 6999 INFO ? openerp.service.server: HTTP service (werkzeug) running on 0.0.0.0:8069
Exception in thread openerp.service.httpd:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in **bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(_self.__args, *_self.__kwargs)
  File "/opt/odoo/server/openerp/service/server.py", line 291, in http_thread
    self.httpd = ThreadedWSGIServerReloadable(self.interface, self.port, app)
  File "/opt/odoo/server/openerp/service/server.py", line 97, in __init**
    handler=RequestHandler)
  File "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 410, in **init**
    HTTPServer.**init**(self, (host, int(port)), handler)
  File "/usr/lib/python2.7/SocketServer.py", line 420, in **init**
    self.server_bind()
  File "/opt/odoo/server/openerp/service/server.py", line 107, in server_bind
    super(ThreadedWSGIServerReloadable, self).server_bind()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 108, in server_bind
    SocketServer.TCPServer.server_bind(self)
  File "/usr/lib/python2.7/SocketServer.py", line 434, in server_bind
    self.socket.bind(self.server_address)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] La dirección ya se está usando
cual sera el problema???????

**Comment by codeadict** [comment]
debes detener un proceso de odoo que ya está corriendo, por eso no puede hacer binding en ese puerto

**Comment by ayepezv** [comment]
De lo que me indicas debo detener el servicio de odoo para que pueda correr y ejecutar nuevamente el comando???  POrque ya e reiniciado por completo el sistema operativo e igual el mismo error me indica. ... Oh como detengo o encuentre ese proceso

**Comment by libreec** [comment]
Ejecuta lo siguiente en tu terminal:

ps -ax | grep server

Vas a obtener una lista de aplicaciones, luego ejecuta:

kill -9 121212

dónde 121212 es el número del proceso que ejecute openerp.py

Con eso puedes correr nuevamente tu servicio.

**Comment by ovnicraft** [comment]
Resuelto en rama 8.0
