### ISSUE TITLE
Error al Validar Factura de Venta

### ISSUE THREAD

**Issue by ocurieles** [odoo-ecuador/odoo-ecuador#81]
Buenas tardes, estimados al intentar validar una factura de venta, recibo el siguiente error:
Odoo Server Error
Traceback (most recent call last):
  File "/home/odoo/odoo8/openerp/http.py", line 537, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/odoo8/openerp/http.py", line 574, in dispatch
    result = self._call_function(*_self.params)
  File "/home/odoo/odoo8/openerp/http.py", line 310, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/home/odoo/odoo8/openerp/service/model.py", line 118, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/home/odoo/odoo8/openerp/http.py", line 307, in checked_call
    return self.endpoint(_a, *_kw)
  File "/home/odoo/odoo8/openerp/http.py", line 803, in __call__
    return self.method(_args, *_kw)
  File "/home/odoo/odoo8/openerp/http.py", line 403, in response_wrap
    response = f(_args, *_kw)
  File "/home/odoo/odoo8/addons/web/controllers/main.py", line 955, in exec_workflow
    return request.session.exec_workflow(model, id, signal)
  File "/home/odoo/odoo8/openerp/http.py", line 1111, in exec_workflow
    r = self.proxy('object').exec_workflow(self.db, self.uid, self.password, model, signal, id)
  File "/home/odoo/odoo8/openerp/http.py", line 879, in proxy_method
    result = dispatch_rpc(self.service_name, method, args)
  File "/home/odoo/odoo8/openerp/http.py", line 115, in dispatch_rpc
    result = dispatch(method, params)
  File "/home/odoo/odoo8/openerp/service/model.py", line 37, in dispatch
    res = fn(db, uid, _params)
  File "/home/odoo/odoo8/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, *_kwargs)
  File "/home/odoo/odoo8/openerp/service/model.py", line 188, in exec_workflow
    return exec_workflow_cr(cr, uid, obj, signal, _args)
  File "/home/odoo/odoo8/openerp/service/model.py", line 182, in exec_workflow_cr
    return execute_cr(cr, uid, obj, 'signal_workflow', [res_id], signal)[res_id]
  File "/home/odoo/odoo8/openerp/service/model.py", line 164, in execute_cr
    return getattr(object, method)(cr, uid, *args, *_kw)
  File "/home/odoo/odoo8/openerp/api.py", line 268, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/odoo/odoo8/openerp/models.py", line 3572, in signal_workflow
    result[res_id] = workflow.trg_validate(uid, self._name, res_id, signal, cr)
  File "/home/odoo/odoo8/openerp/workflow/__init__.py", line 85, in trg_validate
    return WorkflowService.new(cr, uid, res_type, res_id).validate(signal)
  File "/home/odoo/odoo8/openerp/workflow/service.py", line 91, in validate
    res2 = wi.validate(signal)
  File "/home/odoo/odoo8/openerp/workflow/instance.py", line 80, in validate
    wi.process(signal=signal, force_running=force_running, stack=stack)
  File "/home/odoo/odoo8/openerp/workflow/workitem.py", line 120, in process
    ok = self._split_test(activity['split_mode'], signal, stack)
  File "/home/odoo/odoo8/openerp/workflow/workitem.py", line 248, in _split_test
    self._join_test(t[0], t[1], stack)
  File "/home/odoo/odoo8/openerp/workflow/workitem.py", line 257, in _join_test
    WorkflowItem.create(self.session, self.record, activity, inst_id, stack=stack)
  File "/home/odoo/odoo8/openerp/workflow/workitem.py", line 95, in create
    workflow_item.process(stack=stack)
  File "/home/odoo/odoo8/openerp/workflow/workitem.py", line 116, in process
    if not self._execute(activity, stack):
  File "/home/odoo/odoo8/openerp/workflow/workitem.py", line 162, in _execute
    returned_action = self.wkf_expr_execute(activity)
  File "/home/odoo/odoo8/openerp/workflow/workitem.py", line 313, in wkf_expr_execute
    return self.wkf_expr_eval_expr(activity['action'])
  File "/home/odoo/odoo8/openerp/workflow/workitem.py", line 291, in wkf_expr_eval_expr
    result = eval(line, env, nocopy=True)
  File "/home/odoo/odoo8/openerp/tools/safe_eval.py", line 314, in safe_eval
    return eval(c, globals_dict, locals_dict)
  File "", line 1, in <module>
  File "/home/odoo/odoo8/openerp/api.py", line 266, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/home/odoo/odoo-ecuador8/l10n_ec_withdrawing/withdrawing.py", line 847, in action_retention_create
    'period_id': inv.period_id.id
  File "/home/odoo/odoo8/openerp/api.py", line 266, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/home/odoo/odoo8/openerp/models.py", line 4094, in create
    record = self.browse(self._create(old_vals))
  File "/home/odoo/odoo8/openerp/api.py", line 266, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/home/odoo/odoo8/openerp/api.py", line 508, in new_api
    result = method(self._model, cr, uid, _args, *_old_kwargs)
  File "/home/odoo/odoo8/openerp/models.py", line 4214, in _create
    self._check_selection_field_value(cr, user, field, vals[field], context=context)
  File "/home/odoo/odoo8/openerp/api.py", line 268, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/odoo/odoo8/openerp/api.py", line 372, in old_api
    result = method(recs, _args, *_kwargs)
  File "/home/odoo/odoo8/openerp/models.py", line 2260, in _check_selection_field_value
    field.convert_to_cache(value, self)
  File "/home/odoo/odoo8/openerp/fields.py", line 1405, in convert_to_cache
    raise ValueError("Wrong value for %s: %r" % (self, value))
ValueError: "Wrong value for account.retention.type: u'out_invoice'" while evaluating
u'action_retention_create()'

  Su ayuda por favor.

**Comment by ovnicraft** [comment]
@ocurieles prueba las actualizaciones realizadas, la version 8.0 va muy bien ahora.

**Comment by ovnicraft** [comment]
Lo cierro hasta tener nuevas noticias.
