### ISSUE TITLE
Error al tratar de instalar cualquier módulo de la localización

### ISSUE THREAD

**Issue by Jaime2ndQuadrant** [odoo-ecuador/odoo-ecuador#97]
Muestro el error que me da, también adjunto una imagen mostrando los módulos que trato de instalar.
"""
Odoo Server Error
Traceback (most recent call last):
  File "/home/openerp/8.0/openerp/http.py", line 643, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/openerp/8.0/openerp/http.py", line 680, in dispatch
    result = self._call_function(*_self.params)
  File "/home/openerp/8.0/openerp/http.py", line 316, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/home/openerp/8.0/openerp/service/model.py", line 118, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/home/openerp/8.0/openerp/http.py", line 309, in checked_call
    result = self.endpoint(_a, *_kw)
  File "/home/openerp/8.0/openerp/http.py", line 959, in __call__
    return self.method(_args, *_kw)
  File "/home/openerp/8.0/openerp/http.py", line 509, in response_wrap
    response = f(_args, *_kw)
  File "/home/openerp/8.0/addons/web/controllers/main.py", line 900, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/openerp/8.0/addons/web/controllers/main.py", line 888, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, _args, *_kwargs)
  File "/home/openerp/8.0/openerp/api.py", line 250, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/openerp/8.0/openerp/addons/base/module/module.py", line 459, in button_immediate_install
    return self._button_immediate_function(cr, uid, ids, self.button_install, context=context)
  File "/home/openerp/8.0/openerp/api.py", line 250, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/openerp/8.0/openerp/addons/base/module/module.py", line 533, in _button_immediate_function
    registry = openerp.modules.registry.RegistryManager.new(cr.dbname, update_module=True)
  File "/home/openerp/8.0/openerp/modules/registry.py", line 386, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/openerp/8.0/openerp/modules/loading.py", line 338, in load_modules
    loaded_modules, update_module)
  File "/home/openerp/8.0/openerp/modules/loading.py", line 237, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/home/openerp/8.0/openerp/modules/loading.py", line 156, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/home/openerp/8.0/openerp/modules/loading.py", line 98, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/home/openerp/8.0/openerp/tools/convert.py", line 851, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/home/openerp/8.0/openerp/tools/convert.py", line 938, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/home/openerp/8.0/openerp/tools/convert.py", line 801, in parse
    self.parse(rec, mode)
  File "/home/openerp/8.0/openerp/tools/convert.py", line 804, in parse
    self._tags[rec.tag](self.cr, rec, de, mode=mode)
  File "/home/openerp/8.0/openerp/tools/convert.py", line 708, in _tag_record
    id = self.pool['ir.model.data']._update(cr, self.uid, rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode, context=rec_context )
  File "/home/openerp/8.0/openerp/api.py", line 250, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/openerp/8.0/openerp/addons/base/ir/ir_model.py", line 1143, in _update
    res_id = model_obj.create(cr, uid, values, context=context)
  File "/home/openerp/8.0/openerp/api.py", line 250, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/openerp/8.0/openerp/addons/base/ir/ir_ui_view.py", line 353, in create
    context=context)
  File "/home/openerp/8.0/openerp/api.py", line 250, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/openerp/8.0/openerp/api.py", line 354, in old_api
    result = method(recs, _args, *_kwargs)
  File "/home/openerp/8.0/openerp/models.py", line 4151, in create
    record = self.browse(self._create(old_vals))
  File "/home/openerp/8.0/openerp/api.py", line 248, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/home/openerp/8.0/openerp/api.py", line 490, in new_api
    result = method(self._model, cr, uid, _args, *_old_kwargs)
  File "/home/openerp/8.0/openerp/models.py", line 4342, in _create
    recs._validate_fields(vals)
  File "/home/openerp/8.0/openerp/api.py", line 248, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/home/openerp/8.0/openerp/models.py", line 1271, in _validate_fields
    raise ValidationError('\n'.join(errors))
ParseError: "Invalid view definition

Detalles de error:
El elemento '<xpath expr="//label[@for='name']">' no puede ser localizado en la vista padre

Error de contexto:
Vista `res.partner.cedruc.form`
[view_id: 568, xml_id: n/a, model: res.partner, parent_id: 123]
None" while parsing /home/openerp/addons/8.0/odoo-ecuador/l10n_ec_partner/view/partner_view.xml:32, near
<record id="view_res_partner_cedruc_form" model="ir.ui.view">
  <field name="name">res.partner.cedruc.form</field>
  <field name="model">res.partner</field>
  <field name="inherit_id" ref="base.view_partner_form"/>
  <field name="arch" type="xml">
    <data><xpath expr="//label[@for='name']" position="attributes">
      <attribute name="string">Raz&#243;n Social</attribute>
    </xpath>
    <xpath expr="//field[@name='parent_id']" position="after">
      <div>
    <field name="type_ced_ruc" placeholder="Tipo de Identificador" class="oe_inline"/>
    <field name="ced_ruc" placeholder="C&#233;dula / RUC" class="oe_inline"/>
      </div>
      <field name="tipo_persona" placeholder="Tipo de Persona"/>  
    <newline/>
    </xpath>
  </data></field>
</record>
"""
![modulos_l10n_ec_odoo8](https://cloud.githubusercontent.com/assets/920274/15689396/5ef3bacc-2744-11e6-89f2-adbe63dc35bb.png)

**Comment by ovnicraft** [comment]
@Jaime2ndQuadrant por el log es la 8.0, pero por la captura de pantalla veo la 9.0

me puedes confirmar que la version de odoo sea la 8.0 ?

**Comment by Jaime2ndQuadrant** [comment]
doh! cuando clone odoo olvide hacer un checkout a 8.0. 
Pero pensando en eso, los módulos no deberían tener alguna protección contra usuarios?

Un mensaje de error de tipo: "hey! no sea bobo, este módulo es para una versión distinta de odoo!" En lugar de un mensaje tan criptico...

**Comment by ovnicraft** [comment]
@Jaime2ndQuadrant si me gusta la idea del mensaje, lo revisamos y te doy noticias.
Por ahora lo cierro y dejo para comentarlo sobre el mensaje.
